update to Summer16 eID
cp3-llbb/Framework pull request #193
Opened 2016-09-16 15:18 UTC by OlivierBondu

as per
https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2

I'm guessing I may have to update reference trees ? let's try and see...

for updating https://github.com/cp3-llbb/Framework/issues/183

2016-09-16 22:46 UTC, blinkseb commented on python/ElectronsProducer.py
>              ea_R03 = cms.untracked.FileInPath('RecoEgamma/ElectronIdentification/data/PHYS14/effAreaElectrons_cone03_pfNeuHadronsAndPhotons.txt'),
Can you also update this file to `RecoEgamma/ElectronIdentification/data/Summer16/effAreaElectrons_cone03_pfNeuHadronsAndPhotons_80X.txt`?

2016-09-16 22:48 UTC, blinkseb requested changes
Thanks a lot for this! Jenkins test is actually ok, I'm not sure why the status was not updated here...

2016-09-19 09:03 UTC, OlivierBondu commented
updated !

2016-09-19 09:04 UTC, OlivierBondu commented
please test

2016-09-19 09:31 UTC, blinkseb commented
Hm, something is wrong, tests should have failed, unless you updated the ref trees after your last commit? (history suggest it's not the case). One possibility is that the EA factors are actually the same between 7.6 and 8.0. If not, then there's something weird going on. Can you try locally and see if the computed isolation and EA factors for the electrons change from 7.6 to 8.0?

2016-09-19 09:34 UTC, OlivierBondu commented
yes sorry, the commit message is not clear, but I did update the ref trees in the last commit, see https://github.com/cp3-llbb/Framework/pull/193/commits/d955db00d089b07cb62666daed8d9c7dce1f8fda

2016-09-19 09:59 UTC, blinkseb commented
Ah cool! Thanks :)

2016-09-19 09:59 UTC, blinkseb approved these changes

2016-09-19 10:00 UTC, merged