Electrons sf
cp3-llbb/Framework pull request #202
Opened 2016-09-29 12:12 UTC by OlivierBondu

Addresses partly https://github.com/cp3-llbb/Framework/issues/183:
- adds HWW and EGM SFs
- adds HWW trigger SFs and trigger list in `triggers.xml`
- adds EGM 'RECO' SFs (in practice being 'gsf tracking' SFs)

todo:
 - [ ] update ref trees after https://github.com/cp3-llbb/Framework/pull/201 is merged

2016-09-30 07:35 UTC, blinkseb commented
Thanks a lot, looks great!

2016-09-30 08:59 UTC, OlivierBondu commented
PR rebased and ref trees updated

2016-10-01 12:03 UTC, blinkseb requested changes
The `gsfTracking` json file needs to be fixed. Otherwise thanks a lot!

2016-10-01 12:03 UTC, blinkseb commented on data/ScaleFactors/Electron_EGamma_SF2D_gsfTracking.json
> +{
This file is corrupted. I'm not sure why the Framework accept such file, but the resulting values are kind of random.

2016-10-03 08:01 UTC, OlivierBondu commented on data/ScaleFactors/Electron_EGamma_SF2D_gsfTracking.json
> +{
The original file is in the same format as others but seems to have only one bin in pt... it's probably the root cause of all this mess

2016-10-03 08:09 UTC, OlivierBondu commented on data/ScaleFactors/Electron_EGamma_SF2D_gsfTracking.json
> +{
got it, there is a typo in the script: https://github.com/cp3-llbb/Framework/blob/69ee67e3dc6bc773164e43d692012a9dc140ab87/scripts/extractElectronScaleFactors.py#L35, fix and PR update incoming

2016-10-03 08:25 UTC, OlivierBondu commented
PR updated with fixed json files: the bug was also removing the very first SF bin of the files... ref trees updated once more

2016-10-03 08:49 UTC, blinkseb commented on data/ScaleFactors/Electron_EGamma_SF2D_gsfTracking.json
> +{
Thanks a lot for the fix!

2016-10-03 08:50 UTC, blinkseb commented
Ouch, nice catch in the end!

2016-10-03 08:50 UTC, blinkseb approved these changes

2016-10-03 08:51 UTC, merged