Muon scale corrections
cp3-llbb/Framework pull request #204
Opened 2016-10-03 14:59 UTC by OlivierBondu

This PR addresses partly https://github.com/cp3-llbb/Framework/issues/183

list of changes:
   * update the Rochester moment scale correction to the newest version (see [their twiki](https://twiki.cern.ch/twiki/bin/view/CMS/RochcorMuon))
   * introduce the Kalman Muon Calibrator (see [their twiki](https://twiki.cern.ch/twiki/bin/view/CMS/MuonScaleResolKalman))
   * the prescription for related muon scale systematics is not super clear at the moment, so nothing is implemented in this regard

Of course both shouldn't be used at the same time... 

For the review: 
   * you can discard the first commit, which is just dropping old rochcor2015 files and replacing with rochcor2016 ones, the other two are the meat of the changes
   * no update of the reference trees since these corrections are off by default

2016-10-03 15:14 UTC, blinkseb requested changes
Thanks a lot! Good to see that Rochester code is still as ugly as before!

I have some comments, mostly cosmetics. I'm also wondering if it's possible to improve the configuration of the muon producer without the need for the _hardcoded_ code in `Framework.py`. What about adding a new argument to the `addProducer` method to allow the user to pass a custom function to be called once the producer is created, with one argument `isData`. We would then be able to move the KaMuCa configuration block into this new function, located inside `MuonProducer.py`. What do you think?

Otherwise, thanks a lot!

2016-10-03 15:14 UTC, blinkseb commented on README.md
> +git clone -o Analysis https://github.com/bachtis/analysis.git -b KaMuCa_V4 KaMuCa # KalmanMuonCalibrator
No tag or anything more stable? Any update upstream will change our results, which mean hardly reproducible results

2016-10-03 15:14 UTC, blinkseb commented on interface/MuonsProducer.h
> +        KalmanMuonCalibrator *kamucacor;
Please switch to `std::unique_ptr` and drop the destructor

2016-10-03 15:14 UTC, blinkseb commented on src/MuonsProducer.cc
> +            if (event.isRealData())
`{` on the same line

2016-10-03 15:14 UTC, blinkseb commented on src/MuonsProducer.cc
> +                if (!muon.innerTrack().isNull())
Same here

2016-10-03 15:14 UTC, blinkseb commented on src/MuonsProducer.cc
> +            muon.setP4(math::XYZTLorentzVector(TLmu.Px(),TLmu.Py(),TLmu.Pz(),TLmu.E()));
Space after comma

2016-10-03 15:14 UTC, blinkseb commented on src/MuonsProducer.cc
> +        if (applyKaMuCa)
`{` on the same line

2016-10-03 15:14 UTC, blinkseb commented on src/MuonsProducer.cc
> +            TLorentzVector TLmu(muon.px(),muon.py(),muon.pz(),muon.energy());
Why the `TLorentzVector` here? You can use `muon.scaleEnergy()` to rescale the P4

2016-10-03 15:20 UTC, OlivierBondu commented on README.md
> +git clone -o Analysis https://github.com/bachtis/analysis.git -b KaMuCa_V4 KaMuCa # KalmanMuonCalibrator
I just dumbly took the setup instructions, we can switch to their latest commit of today ?

2016-10-03 15:24 UTC, OlivierBondu commented
I just learned I did not apply KaMuCa for MC in the correct order, please don't merge before I remove the label :)

2016-10-03 15:25 UTC, blinkseb commented on README.md
> +git clone -o Analysis https://github.com/bachtis/analysis.git -b KaMuCa_V4 KaMuCa # KalmanMuonCalibrator
Should be enough thanks :+1:

2016-10-03 15:44 UTC, OlivierBondu commented on src/MuonsProducer.cc
> +            TLorentzVector TLmu(muon.px(),muon.py(),muon.pz(),muon.energy());
ha, correct, just out of laziness I copied the rochcor syntax ;)

2016-10-03 15:59 UTC, OlivierBondu commented
PR updated

2016-10-04 08:27 UTC, OlivierBondu commented
PR updated with requested changes + storing the value of the correction factor

I did update the reference trees since this is now adding one branch

2016-10-04 08:45 UTC, blinkseb requested changes
One last fix and it's good to go :+1:

2016-10-04 08:45 UTC, blinkseb commented on interface/MuonsProducer.h
> +        BRANCH(kamuca_correction, std::vector<float>);
One branch is enough since you explicitly check if both method are used at the same time. Something like `scale_correction_factor`?

2016-10-04 09:09 UTC, OlivierBondu commented on interface/MuonsProducer.h
> +        BRANCH(kamuca_correction, std::vector<float>);
corrected in the latest commit

2016-10-04 09:09 UTC, OlivierBondu commented on interface/MuonsProducer.h
> +        KalmanMuonCalibrator *kamucacor;
done

2016-10-04 09:09 UTC, OlivierBondu commented on src/MuonsProducer.cc
> +            if (event.isRealData())
done

2016-10-04 09:09 UTC, OlivierBondu commented on src/MuonsProducer.cc
> +                if (!muon.innerTrack().isNull())
done

2016-10-04 09:09 UTC, OlivierBondu commented on src/MuonsProducer.cc
> +            muon.setP4(math::XYZTLorentzVector(TLmu.Px(),TLmu.Py(),TLmu.Pz(),TLmu.E()));
done (also other places)

2016-10-04 09:09 UTC, OlivierBondu commented on src/MuonsProducer.cc
> +        if (applyKaMuCa)
done

2016-10-04 09:22 UTC, blinkseb approved these changes

2016-10-04 09:23 UTC, blinkseb commented
Thanks a lot!

2016-10-04 09:24 UTC, merged