Updates for CMSSW_9_4_X
cp3-llbb/Framework pull request #280
Opened 2018-08-08 13:12 UTC by pieterdavid

I checked out the Framework in CMSSW_9_4_9, removed everything that said 80X or 'Moriond17' etc., and tried to make things run... so there will be differences, and I may have been too enthusiastically removing things in some places - my main aim was to provide a "clean" starting point, but feel free to point out if something doesn't make sense.

Anticipating a few questions:
- on-demand scheduling requires a `cms.Task` to be associated with the process or path for each `edm::EDProducer`. This required quite a bit of trial-and-error with redoJEC etc., but the tests should run now
- I turned off EGM regression and smearing for now, because the way this works changed (new recipes at https://twiki.cern.ch/twiki/bin/view/CMS/EgammaMiniAODV2 and https://twiki.cern.ch/twiki/bin/view/CMS/EgammaPostRecoRecipes) and I haven't implemented the new recipes yet.

2018-08-14 14:21 UTC, pieterdavid commented
I went through the diffs...
For `unit_tests_data.py` the differences are minor: all scale factors gone (I removed them), `electron_expectedMissingInnerHits`, `(fat)jet_pfDeepCSVJetTags_probcc` (it seems not to be there in this version of the deepcsv) and `muon_isMedium2016`. The former and latter will probably be needed still, so I can put them back easily. There are also differences in `jet_pfDeepCSVJetTags_probc` (maybe the merged `probc` and `probcc`?), and in the electron IDs because I removed them... maybe in hindsight I shouldn't have.
For `unit_test_mc_with_db.py` the same, plus the PU weights which I also removed.
For `unit_test_mc.py` there are more differences... I turned off the electron smearing and regression (the recipes changed, see [this twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaMiniAODV2#Energy_Scale_and_Smearing), I didn't get to implementing that).
Also the jet, jet systematic variation and MET branches changed. For the former two I suppose that would be because we pick up newer calibrations/recipes somehow, for the MET I'm reasonably certain (I saw code changes that needed the config to be adjusted). Does that make sense?

2018-09-14 12:53 UTC, OlivierBondu requested changes
Thanks!

sorry for the late review, only minor changes :)

2018-09-14 12:53 UTC, OlivierBondu commented on README.md
> +source setup_project_with_framework.sh --branch BRANCH ## select a branch
maybe we could assume here the default branch should be 94X ? I would expect newcomers (and myself) to copy paste blindly in a terminal without checking that there is need to replace BRANCH by whatever

2018-09-14 12:53 UTC, OlivierBondu commented on README.md
> +perform an initial build, and add your and your colleagues' forks on GitHub as remotes for your ``Framework`` clone.
speaking of which, maybe we could profit from this cleanup PR to cleanup [these](https://github.com/cp3-llbb/Framework/blob/CMSSW_8_0_6p/first_setup.sh#L17-L27) ? Do you know if there would exist an api to get the list automatically ? This would remove the pain of updating the list...

2018-09-14 12:53 UTC, OlivierBondu commented on interface/ElectronsProducer.h
> -
I assume you are removing this because it will be in the ID itself ?

2018-09-14 12:53 UTC, OlivierBondu commented on python/ElectronsProducer.py
> -                'egmGsfElectronIDs:mvaEleID-Spring16-HZZ-V1-wpLoose'
there is no ID at all ??

2018-09-14 12:53 UTC, OlivierBondu commented on bootstrap_jenkins.sh
> +git clone -o upstream https://github.com/bachtis/analysis.git -b KaMuCa_V4 KaMuCa
KaMuCa has not been updated in forever, it most probably won't be up to date either for 94X ?

2018-09-14 12:53 UTC, OlivierBondu commented on python/Framework.py
> -                allowUnscheduled = cms.untracked.bool(True)
why not keep the option explicit and put it to false instead ?

2018-09-14 12:53 UTC, OlivierBondu commented on python/Tools.py
> +        [ "patCaloMet", "patCHSMet", "pfMetCHS", "pfCHS", "patTrkMet", "pfMetTrk", "pfTrk", "metrawCaloNewJEC" ])
I will trust you on this one, I don't know JEC nor MET :smile:

2018-09-14 12:53 UTC, OlivierBondu commented on test/unit_tests_mc.py
> +framework.applyMuonCorrection("kamuca", tag="MC_80X_13TeV")
please comment this line out

2018-09-18 11:24 UTC, pieterdavid commented on python/Tools.py
> +        [ "patCaloMet", "patCHSMet", "pfMetCHS", "pfCHS", "patTrkMet", "pfMetTrk", "pfTrk", "metrawCaloNewJEC" ])
This is pure trial&error (but unfortunately needed with tasks, until we get a cms.Task-proof version of it): I went up to the point where I don't get errors about products that don't exist, and neither about modules that are not defined

2018-09-18 11:24 UTC, pieterdavid commented on python/Framework.py
> -                allowUnscheduled = cms.untracked.bool(True)
see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideUnscheduledExecution#Usage (it's always true, so this does not have any effect)

2018-09-18 11:24 UTC, pieterdavid commented on bootstrap_jenkins.sh
> +git clone -o upstream https://github.com/bachtis/analysis.git -b KaMuCa_V4 KaMuCa
I only checked it was the latest... disabled now

2018-09-18 11:24 UTC, pieterdavid commented on python/ElectronsProducer.py
> -                'egmGsfElectronIDs:mvaEleID-Spring16-HZZ-V1-wpLoose'
There are 'Fall17' 94X IDs to be used for 2017 and 2018, but the twiki doesn't mention reprocessed 2016 data.

2018-09-18 11:24 UTC, pieterdavid commented on interface/ElectronsProducer.h
> -
yes, I suppose that with the reprocessing there will be one ID for 2016-2017-2018 that can be used without additional ad-hoc cuts.

2018-09-18 11:24 UTC, pieterdavid commented on README.md
> +perform an initial build, and add your and your colleagues' forks on GitHub as remotes for your ``Framework`` clone.
Of course there is... it return json, so I made the script in python. It takes "active" forks as all those that have been pushed to during the last year, and should also work for other packages - assuming the base repository is set as 'upstream', or under 'cp3-llbb'. There maybe other things missing.

2018-09-18 11:24 UTC, pieterdavid commented on README.md
> +source setup_project_with_framework.sh --branch BRANCH ## select a branch
Indeed, that makes sense

2018-09-28 10:03 UTC, OlivierBondu approved these changes

2018-09-28 10:04 UTC, OlivierBondu commented
the `updateremotes` script is just perfect :) thanks for the other fixes !

Do you know why Jenkins fails ? Is it just the outdated ref trees ?

2018-11-20 16:13 UTC, closed without merging

2018-11-20 16:21 UTC, pieterdavid commented
I changed the definition of the target branch, so reopening as a new PR, https://github.com/cp3-llbb/Framework/pull/284